### PR TITLE
fix: Fix list and listcaptain

### LINKED ISSUE #241: Missing empty list error message for list and listcaptain
When the list is empty, list and listcaptain should throw an error instead of "Listed all players"

### PR DESCRIPTION
**Pull request by ChekaLowQiJun**
Fixes #241

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/ListCaptainCommandTest.java [hunk 1]
```diff
@@ -27,14 +30,27 @@ public void setUp() {
...
+    }
+
+    @Test
+    public void execute_noCaptains_throwsCommandException() {
+        // Clear all captains from the model
+        model.updateFilteredPersonList(person -> !person.isCaptain());
+
+        ListCaptainCommand command = new ListCaptainCommand();
+        CommandException exception = assertThrows(CommandException.class, () -> command.execute(model));
+        assertEquals("There are currently no captains in the PlayBook.", exception.getMessage());
```
Comment (Juink4i) [inline src/test/java/seedu/address/logic/commands/ListCaptainCommandTest.java]: can make use of Messages.MESSAGE_NO_CAPTAINS

File: src/test/java/seedu/address/logic/commands/ListCommandTest.java [hunk 2]
```diff
@@ -36,4 +40,14 @@ public void execute_listIsFiltered_showsEverything() {
...
     }
+
+    @Test
+    public void execute_emptyAddressBook_throwsCommandException() {
+        // Create an empty model
+        Model emptyModel = new ModelManager(new AddressBook(), new UserPrefs());
+
+        ListCommand command = new ListCommand();
+        CommandException exception = assertThrows(CommandException.class, () -> command.execute(emptyModel));
+        assertEquals("There are currently no players in the PlayBook.", exception.getMessage());
```
Comment (Juink4i) [inline src/test/java/seedu/address/logic/commands/ListCommandTest.java]: can use Messages.MESSAGE_NO_PLAYERS

**Review by Juink4i — APPROVED** [review]
LGTM js some small things to change
